In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [3]:
a = [1,2,3,4]
a

[1, 2, 3, 4]

In [4]:
l =[[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
arr= np.zeros((4,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [8]:
arr = np.ones((4,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [9]:
arr = np.linspace(0,100,5)
arr

array([  0.,  25.,  50.,  75., 100.])

In [10]:
np.random.rand(10)

array([0.57425019, 0.32268225, 0.69356564, 0.91155252, 0.64495477,
       0.86819647, 0.25805217, 0.42839282, 0.80625941, 0.04718174])

In [11]:
np.random.randn(10)

array([-3.05710035e+00, -2.46543294e-03,  2.39411551e+00,  1.05375932e+00,
        1.92400401e+00,  5.24031260e-01,  3.93585169e-01, -1.38020246e+00,
        5.10081202e-01, -9.55390991e-01])

In [12]:
np.random.randint(10)

3

In [13]:
np.random.randint(10,20)

15

In [14]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
arr.shape

(3, 3)

In [16]:
arr.dtype

dtype('int64')

In [17]:
arr.size


9

In [18]:
arr.min()

np.int64(1)

In [19]:
arr.max()

np.int64(9)

In [20]:
arr.sum()

np.int64(45)

In [21]:
np.sum(arr, axis = 0)

array([12, 15, 18])

In [22]:
np.sum(arr, axis = 1)

array([ 6, 15, 24])

In [23]:
arr.mean()

np.float64(5.0)

In [24]:
arr.std()

np.float64(2.581988897471611)

In [25]:
arr.argmax()

np.int64(8)

In [26]:
arr.argmin()

np.int64(0)

In [27]:
arr = np.arange(1, 31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [28]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [37]:
#resize
arr = arr.reshape(5,6)

In [38]:
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [40]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [45]:
arr[1:5]

array([11, 12, 13, 14, 15])

In [46]:
arr[:5]

array([11, 12, 13, 14, 15])

In [50]:
array_slice = arr[0::5]
array_slice

array([11, 16])

In [69]:
arr =np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [70]:
arr[5,4]

np.int64(30)

In [71]:
slice = arr[0:2, 1:3]
slice

array([[2, 3],
       [7, 8]])

In [84]:
slice = arr[3:6, 3:5]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [85]:
slice = arr[3:, 3:]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [90]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

In [96]:
arr= np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [97]:
bool_index = arr %2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [98]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])

In [100]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [101]:
a1+a2

array([ 7,  9, 11, 13, 15])

In [102]:
l = [10, 20, 30, 40 , 50]
arr = np.array(l)

In [104]:
for i in l:
    print(i +10)

20
30
40
50
60


In [105]:
arr +10

array([20, 30, 40, 50, 60])

In [108]:
arr = np.arange(1,26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [110]:
arr * 2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50]])

In [111]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [112]:
slice = a[:5]
slice = a *2
slice

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40])

In [128]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [129]:
A

array([[1, 2],
       [3, 4]])

In [130]:
B

array([[5, 6],
       [7, 8]])

In [131]:
A @ B

array([[19, 22],
       [43, 50]])

In [132]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [133]:
A.T

array([[1, 3],
       [2, 4]])

In [134]:
B.T

array([[5, 7],
       [6, 8]])

In [142]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [143]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [144]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [141]:
np.column_stack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [145]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [149]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [150]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]